In [6]:
# Dependencies and Setup

import pandas as pd
import numpy as np

# Files to Load

train_file = "train_file_427_v2.csv"

In [7]:
# Read Train File and store into Pandas data frame
train_read = pd.read_csv(train_file)
train_data = train_read.rename(index=str, columns={"id": "user_id"})
train_data.head()

,user_id,date_account_created,timestamp_first_active,date_first_booking,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,...,your_trips_1,message_post_y_1,at_checkpoint_y_1,dashboard_y_1,cancellation_policies_y_1,edit_profile_1,oauth_login_1,Male,Male_u,age_b
0,gxn3p5htnn,2010-06-28,20090319043255,NaN,NaN,facebook,0,en,direct,direct,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
1,820tgsjxq7,2011-05-25,20090523174809,NaN,38.0,facebook,0,en,seo,google,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1
2,4ft3gnwmtx,2010-09-28,20090609231247,2010-08-02,56.0,basic,3,en,direct,direct,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
3,bjjt8pjhuk,2011-12-05,20091031060129,2012-09-08,42.0,facebook,0,en,direct,direct,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1
4,87mebub9p4,2010-09-14,20091208061105,2010-02-18,41.0,basic,0,en,direct,direct,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1

In [8]:
# developed the booking = 0/1 based on booking date
train_data['stringdate'] = train_data.date_first_booking.astype(str)
train_data.loc[train_data['stringdate'] == 'nan', 'booked'] = 0
train_data.loc[train_data['stringdate'] != 'nan', 'booked'] = 1

print(train_data.booked.value_counts())
train_data.head()

0.0    124543
1.0     88908
Name: booked, dtype: int64

,user_id,date_account_created,timestamp_first_active,date_first_booking,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,...,message_post_y_1,at_checkpoint_y_1,dashboard_y_1,cancellation_policies_y_1,edit_profile_1,oauth_login_1,Male,Male_u,age_b,booked
0,gxn3p5htnn,2010-06-28,20090319043255,NaN,NaN,facebook,0,en,direct,direct,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0
1,820tgsjxq7,2011-05-25,20090523174809,NaN,38.0,facebook,0,en,seo,google,...,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1,0.0
2,4ft3gnwmtx,2010-09-28,20090609231247,2010-08-02,56.0,basic,3,en,direct,direct,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,1.0
3,bjjt8pjhuk,2011-12-05,20091031060129,2012-09-08,42.0,facebook,0,en,direct,direct,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1,1.0
4,87mebub9p4,2010-09-14,20091208061105,2010-02-18,41.0,basic,0,en,direct,direct,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1,1.0

In [9]:
train_data.to_csv('train_data_booked.csv')

In [ ]:
train_data.plot.bar(x='')